name: CreativeControl
version: 2.0
main: com.mith.CreativeControl.CreativeControl
api-version: 1.19
commands:
  ccreload:
    description: Primary plugin command
permissions:
  cosmetics.admin:
    description: Allows you to bypass creative control
    default: op